baseURL = '/'
languageCode = 'en-us'
title = '@kzoeps gi zimchu'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A kzoeps blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'kuzu kuzu wai!'
homeIntroContent = """
Zoepa is a 24-year-old software developer from Bhutan who is currently trying to find his footing as he graduates from college this May. Combined with a mix of laziness and a longing for home, he is moving back to try and find a life at home. Will he succeed or fail? We shall find out in the coming 2 years. 

Aside from technology, he loves yapping about things he knows and doesn't, especially anything related to Bhutan. You can find him usually at mama's talking about Bhutan's economics, the future, and the music scene.

You can check out my blogs [here](https://kzoeps.substack.com) or read some musings [here](/pensieve)
"""

# Collection to display on home
homeCollectionTitle = 'Thoughts'
homeCollection = 'pensieve'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'
faviconPath = '/'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "github"
url = "https://www.github.com/kzoeps/"

[[params.social]]
name = "substack"
url = "https://kzoeps.substack.com"

[[params.social]]
name = "twitter"
url = "https://twitter.com/kzoeps"

[[params.social]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/12949177/kzoeps"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "pensieve"
url = "/pensieve"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "Namthar"
url = "/namthar"

[[params.menu]]
name = "posties"
url = "https://posties.kzoeps.com/posties"

[[params.menu]]
name = "bop-stop"
url = "https://posties.kzoeps.com/bop-stop"

[[params.menu]]
name = "notebook"
url = "/notebook"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "kzoeps/kzoeps.me"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
